# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - test

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              containerRegistry: "Dockerhub"
              repository: "artsdatabanken/stedsnavn-api"
              command: "build"
              Dockerfile: "**/Dockerfile"
              tags: "test"
          - task: Docker@2
            displayName: Publish image
            inputs:
              containerRegistry: "Dockerhub"
              repository: "artsdatabanken/stedsnavn-api"
              command: "push"
              tags: "test"
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                ls -l
                cd src
                ls -l
          - task: CopyFiles@2
            displayName: "Copy scripts"
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/data/'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/'

          - publish: "$(Build.ArtifactStagingDirectory)/"
            displayName: "Publish script"
            artifact: drop
